-- creating the vaccination table 
CREATE TABLE covid_vaccination
(
iso_code varchar,
	continent VARCHAR,
	location VARCHAR,
	date DATE,
	population VARCHAR,
	total_tests VARCHAR,
	new_tests VARCHAR,
	total_tests_per_thousand VARCHAR,
	new_tests_per_thousand VARCHAR,
	new_tests_smoothed VARCHAR,
	new_tests_smoothed_per_thousand VARCHAR,
	positive_rate VARCHAR,
	tests_per_case VARCHAR,
	tests_units VARCHAR,
	total_vaccinations VARCHAR,
	people_vaccinated VARCHAR,
	people_fully_vaccinated VARCHAR,
	total_boosters VARCHAR,
	new_vaccinations VARCHAR,
	new_vaccinations_smoothed VARCHAR,
	total_vaccinations_per_hundred VARCHAR,
	people_vaccinated_per_hundred VARCHAR,
	people_fully_vaccinated_per_hundred VARCHAR,
	total_boosters_per_hundred VARCHAR,
	new_vaccinations_smoothed_per_million VARCHAR,
	new_people_vaccinated_smoothed VARCHAR,
	new_people_vaccinated_smoothed_per_hundred VARCHAR,
	stringency_index VARCHAR,
	population_density VARCHAR,
	median_age VARCHAR,
	aged_65_older VARCHAR,
	aged_70_older VARCHAR,
	gdp_per_capita VARCHAR,
	extreme_poverty VARCHAR,
	cardiovasc_death_rate VARCHAR,
	diabetes_prevalence VARCHAR,
	female_smokers VARCHAR,
	male_smokers VARCHAR,
	handwashing_facilities VARCHAR,
	hospital_beds_per_thousand VARCHAR,
	life_expectancy VARCHAR,
	human_development_index VARCHAR,
	excess_mortality_cumulative_absolute VARCHAR,
	excess_mortality_cumulative VARCHAR, 
	excess_mortality VARCHAR,
	excess_mortality_cumulative_per_million VARCHAR
)


-- creating the covid_death table 
CREATE TABLE covid_death(iso_code VARCHAR ,continent VARCHAR,
	location VARCHAR,
	date DATE,
	population VARCHAR,
	total_cases VARCHAR,
	new_cases VARCHAR,
	new_cases_smoothed VARCHAR,
	total_deaths VARCHAR,
	new_deaths VARCHAR,
	new_deaths_smoothed VARCHAR,
	total_cases_per_million VARCHAR,
	new_cases_per_million VARCHAR,
	new_cases_smoothed_per_million VARCHAR,
	total_deaths_per_million VARCHAR,
	new_deaths_per_million VARCHAR,
	new_deaths_smoothed_per_million VARCHAR,
	reproduction_rate VARCHAR,
	icu_patients VARCHAR,
	icu_patients_per_million VARCHAR ,
	hosp_patients VARCHAR,
	hosp_patients_per_million VARCHAR,
	weekly_icu_admissions VARCHAR,
	weekly_icu_admissions_per_million VARCHAR,
	weekly_hosp_admissions VARCHAR,
	weekly_hosp_admissions_per_million VARCHAR
						 )


